# Generated by Django 4.1.5 on 2023-01-19 12:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouqet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название букета')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(db_index=True, decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('size', models.CharField(max_length=100, verbose_name='Размер Букета')),
                ('flowers', models.TextField(verbose_name='Состав букета')),
                ('picture', models.CharField(max_length=200, verbose_name='Ссылка на изображение')),
            ],
            options={
                'verbose_name': 'Bouqet',
                'verbose_name_plural': 'Bouqets',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефонный номер')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название события')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес доставки букета')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='flower_app.customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bouqet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='flower_app.bouqet', verbose_name='Товар')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='flower_app.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order items',
            },
        ),
        migrations.AddField(
            model_name='bouqet',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouqets', to='flower_app.event', verbose_name='Событие'),
        ),
    ]
