# Generated by Django 4.1.5 on 2023-01-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouqet',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bouqets', to='flower_app.event', verbose_name='Событие'),
        ),
    ]
