# Generated by Django 4.1.5 on 2023-01-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0002_alter_bouqet_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_time',
            field=models.CharField(choices=[('1', '10:00-12:00'), ('2', '12:00-14:00'), ('3', '14:00-16:00'), ('4', '16:00-18:00'), ('5', '18:00-20:00'), ('now', 'Как можно скорее')], db_index=True, default='now', max_length=20, verbose_name='Время доставки'),
        ),
    ]
