# Generated by Django 4.1.5 on 2023-01-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_app', '0003_order_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Идентиф-р платежа'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', 'Ожидает оплаты'), ('SUCCESS', 'Оплачено'), ('CANCELLED', 'Отменен')], db_index=True, default='UNPROCESSED', max_length=20, verbose_name='Статус Заказа'),
        ),
    ]
