name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build and Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: KustovAA/flower-shop/flower-shop
          registry: ghcr.io
          username: KustovAA
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: latest

      - name: Deploy package to Yandex Cloud
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: 22
          username: KustovAA
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd flower-shop
            git pull
            docker compose pull
            docker compose down
            docker compose --env-file .env up -d
